### ISSUE TITLE
Local install doesnt work

### ISSUE THREAD

**Issue by RikCost** [xxond/disco-limbic-dialogue#1]
I successful install requirement, but then i try python client_cmd.py i get this:
D:\disco-limbic-dialogue-main>python client_cmd.py
You are using a model of type phi-msft to instantiate a model of type phi. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "D:\disco-limbic-dialogue-main\client_cmd.py", line 22, in <module>
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yaroslav\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\models\auto\auto_factory.py", line 553, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yaroslav\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dynamic_module_utils.py", line 499, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yaroslav\AppData\Local\Programs\Python\Python311\Lib\site-packages\transformers\dynamic_module_utils.py", line 199, in get_class_in_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yaroslav\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Yaroslav/.cache\huggingface\modules\transformers_modules\microsoft\phi-2\710686f446f02286c858c11f052acb87c306ddd2\modeling_phi.py", line 29, in <module>
    from transformers.cache_utils import Cache, DynamicCache
ModuleNotFoundError: No module named 'transformers.cache_utils'
![image](https://github.com/xxond/disco-limbic-dialogue/assets/69048938/b39c3961-ffe9-403f-b57a-7559e9cc33b8)

**Comment by xxond** [comment]
Hey @RikCost 

it looks like some updated from

- transformers lib
- Microsoft/phi2 

broke something on my side, so I updated model files on hf and pinned some versions in reqs, now should be working, pull lates changes and reinstall dependences.

May I ask you why do you interested in this project? just curious

**Comment by RikCost** [comment]
@xxond I'm into neural networks and also love Disco Elysium, I recently tried generating dialog like in the game and it came out surprisingly pretty good, so I thought if I trained llm on dialogs from the game then it should be even better and more authentic! I was looking for a simple way to get the files I needed and in that search I came across this repository.

**Comment by RikCost** [comment]
@xxond Is it possible to find your dataset or lora anywhere? It's just that while phi-2 is pretty good, phi-3 and other llm's have recently come out that are head and shoulders better.

**Comment by RikCost** [comment]
All work
![image](https://github.com/xxond/disco-limbic-dialogue/assets/69048938/ab6bb343-2f6f-444b-a7a3-453c23276c77)

**Comment by xxond** [comment]
@RikCost 

IMO model in this repo is pretty bad one, but it could be better, I just moved to other projects.

share any of your contact info so I can share everything I have on that

**Comment by RikCost** [comment]
@xxond https://pastebin.com/CmKNPyrw
password: cym7RFWu6p
p.s. Updated
